blank_issues_enabled: true
contact_links:
    - name: zksync-ethers v5 SDK documentation page
      url: https://docs.zksync.io/build/sdks/js/getting-started.html
      about: Please refer to the documentation for immediate answers.
    - name: zksync-ethers v6 SDK documentation page
      url: https://docs.zksync.io/build/sdks/js/zksync-ethers/getting-started.html
      about: Please refer to the documentation for immediate answers.