/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type TransactionStruct = {
  txType: BigNumberish;
  from: BigNumberish;
  to: BigNumberish;
  gasLimit: BigNumberish;
  gasPerPubdataByteLimit: BigNumberish;
  maxFeePerGas: BigNumberish;
  maxPriorityFeePerGas: BigNumberish;
  paymaster: BigNumberish;
  nonce: BigNumberish;
  value: BigNumberish;
  reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
  data: BytesLike;
  signature: BytesLike;
  factoryDeps: BytesLike[];
  paymasterInput: BytesLike;
  reservedDynamic: BytesLike;
};

export type TransactionStructOutput = [
  txType: bigint,
  from: bigint,
  to: bigint,
  gasLimit: bigint,
  gasPerPubdataByteLimit: bigint,
  maxFeePerGas: bigint,
  maxPriorityFeePerGas: bigint,
  paymaster: bigint,
  nonce: bigint,
  value: bigint,
  reserved: [bigint, bigint, bigint, bigint],
  data: string,
  signature: string,
  factoryDeps: string[],
  paymasterInput: string,
  reservedDynamic: string
] & {
  txType: bigint;
  from: bigint;
  to: bigint;
  gasLimit: bigint;
  gasPerPubdataByteLimit: bigint;
  maxFeePerGas: bigint;
  maxPriorityFeePerGas: bigint;
  paymaster: bigint;
  nonce: bigint;
  value: bigint;
  reserved: [bigint, bigint, bigint, bigint];
  data: string;
  signature: string;
  factoryDeps: string[];
  paymasterInput: string;
  reservedDynamic: string;
};

export interface FunctionRestrictionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchUpdateFunctionWhitelist"
      | "canPayForTransaction"
      | "isFunctionWhitelisted"
      | "name"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateFunctionWhitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FunctionWhiteListUpdated" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchUpdateFunctionWhitelist",
    values: [AddressLike[], BytesLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "canPayForTransaction",
    values: [TransactionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isFunctionWhitelisted",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFunctionWhitelist",
    values: [AddressLike, BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchUpdateFunctionWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canPayForTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFunctionWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFunctionWhitelist",
    data: BytesLike
  ): Result;
}

export namespace FunctionWhiteListUpdatedEvent {
  export type InputTuple = [
    contractAddress: AddressLike,
    selector: BytesLike,
    status: boolean
  ];
  export type OutputTuple = [
    contractAddress: string,
    selector: string,
    status: boolean
  ];
  export interface OutputObject {
    contractAddress: string;
    selector: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FunctionRestriction extends BaseContract {
  connect(runner?: ContractRunner | null): FunctionRestriction;
  waitForDeployment(): Promise<this>;

  interface: FunctionRestrictionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchUpdateFunctionWhitelist: TypedContractMethod<
    [
      _targetContracts: AddressLike[],
      _selectors: BytesLike[],
      _statuses: boolean[]
    ],
    [void],
    "nonpayable"
  >;

  canPayForTransaction: TypedContractMethod<
    [_transaction: TransactionStruct],
    [boolean],
    "view"
  >;

  isFunctionWhitelisted: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFunctionWhitelist: TypedContractMethod<
    [_targetContract: AddressLike, _selector: BytesLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchUpdateFunctionWhitelist"
  ): TypedContractMethod<
    [
      _targetContracts: AddressLike[],
      _selectors: BytesLike[],
      _statuses: boolean[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canPayForTransaction"
  ): TypedContractMethod<[_transaction: TransactionStruct], [boolean], "view">;
  getFunction(
    nameOrSignature: "isFunctionWhitelisted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFunctionWhitelist"
  ): TypedContractMethod<
    [_targetContract: AddressLike, _selector: BytesLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FunctionWhiteListUpdated"
  ): TypedContractEvent<
    FunctionWhiteListUpdatedEvent.InputTuple,
    FunctionWhiteListUpdatedEvent.OutputTuple,
    FunctionWhiteListUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FunctionWhiteListUpdated(address,bytes4,bool)": TypedContractEvent<
      FunctionWhiteListUpdatedEvent.InputTuple,
      FunctionWhiteListUpdatedEvent.OutputTuple,
      FunctionWhiteListUpdatedEvent.OutputObject
    >;
    FunctionWhiteListUpdated: TypedContractEvent<
      FunctionWhiteListUpdatedEvent.InputTuple,
      FunctionWhiteListUpdatedEvent.OutputTuple,
      FunctionWhiteListUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
